
# single file or a path to a files. Filenames for tracks and videos should be the same.
track_path: "/home/fatemeh/Downloads/fish/mot_data/ms_exp1/mots/8_1_ms_exp1.txt" # Value: Path . mot format (.txt or .zip). 
video_path: "/home/fatemeh/Downloads/fish/mot_data/vids/8_1.mp4" # Value: Path . video file extension .mp4.
save_path: "/home/fatemeh/Downloads/fish/mot_data/images/8_1/ms_exp1" # Value: Path # vids_tracks
save_images: yes # Value: yes|no or true|false . Save images with tracks. 
# format: 06d # files are saved with this format. e.g. name_0000123.txt the format is '06d'. e.g. name_123.txt the format is ''